export const EventNames = {
  ASTROID_ADDED: "astroidAdded",
  BULLET: "bullet",
  ENEMY_BULLET: "enemyBullet",
  ENEMY_DEAD: "enemyDead",
  ENEMY_ROTATE: "enemyRotate",
  HERO_ADDED: "heroAdded",
  MOVE: "move",
  MOVE_DOWN: "movePlayerDown",
  MOVE_LEFT: "movePlayerLeft",
  MOVE_RIGHT: "movePlayerRight",
  MOVE_UP: "movePlayerTop",
  NEW_PLAYER_JOINED: "newPlayerJoined",
  PLAYER_DEAD: "playerDead",
  PLAYER_LEFT: "playerleft",
  ROTATE: "rotate",
};
