export const EventNames = {
  MOVE_LEFT: "movePlayerLeft",
  MOVE_RIGHT: "movePlayerRight",
  MOVE_UP: "movePlayerTop",
  MOVE_DOWN: "movePlayerDown",
  PLAYER_LEFT: "playerleft",
  NEW_PLAYER_JOINED: "newPlayerJoined",
  MOVE: "move",
  BULLET: "bullet",
  ROTATE: "rotate",
  ENEMY_ROTATE: "enemyRotate",
  PLAYER_DEAD: "playerDead",
  ENEMY_DEAD: "enemyDead",
  ASTROID_ADDED: "astroidAdded",
};
